# -*- coding: utf-8 -*-
"""Aplicación empírica.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15924OllBnsBjk1xzGbby0qmQ8p-hNCM4
"""

from google.colab import drive
drive.mount('/content/drive')

import numpy as np
from scipy.integrate import quad_vec, quad
from scipy.stats import norm
from scipy.optimize import minimize, brentq
import matplotlib; matplotlib.use('Agg')
import matplotlib.pyplot as plt
import os, warnings; warnings.filterwarnings('ignore')
import pandas as pd
import io
import csv

OUT = "figuras_cap5"; os.makedirs(OUT, exist_ok=True)
plt.rcParams.update({'font.family':'serif','font.size':11,
                     'axes.labelsize':12,'figure.dpi':150,'lines.linewidth':1.8})
COLORS = ['#2166ac','#d6604d','#4dac26','#8073ac']

# ═══════════════════════════════════════════════════════════════════
#  DATOS DE MERCADO
# ═══════════════════════════════════════════════════════════════════

def descargar_opciones():
    """Descarga opciones SPY a ~90 días vía yfinance."""
    try:
        import yfinance as yf
        from datetime import datetime, timedelta
        spy  = yf.Ticker("SPY")
        S0   = spy.history(period="1d")["Close"].iloc[-1]
        exps = spy.options
        hoy  = datetime.today()
        exp  = min(exps, key=lambda d: abs(
                   datetime.strptime(d,"%Y-%m-%d")-(hoy+timedelta(days=90))))
        T     = (datetime.strptime(exp,"%Y-%m-%d")-hoy).days/365.0
        chain = spy.option_chain(exp).calls
        chain = chain[(chain["impliedVolatility"]>0.01) &
                      (chain["impliedVolatility"]<2.0)  &
                      (chain["volume"]>10) &
                      (chain["strike"]>0.80*S0) &
                      (chain["strike"]<1.20*S0)]
        chain["mid"] = (chain["bid"]+chain["ask"])/2
        chain = chain[chain["mid"]>0.05]
        print(f"✓ Datos reales SPY: S0={S0:.2f}, exp={exp}, n={len(chain)}")
        return S0, 0.05, T, chain[["strike","mid"]].reset_index(drop=True)
    except Exception as e:
        print(f"✗ Sin datos reales ({e}). Usando referencia de literatura.")
        return None

def datos_referencia():
    """
    Parámetros de referencia calibrados al S&P 500.
    Heston (1993, Tabla 2) y Guo (2021).
    S0=5000, r=5%, T=3 meses.
    """
    S0, r, T = 5000.0, 0.05, 0.25
    K_arr = np.linspace(0.80*S0, 1.20*S0, 22)
    # "Mercado" = Heston + ruido ~ 0.5%
    p_ref = np.array([heston_call(S0,K,T,r,2.0,0.04,0.30,-0.70,0.04)
                      for K in K_arr])
    np.random.seed(0)
    p_mkt = p_ref + np.random.normal(0, p_ref*0.005)
    import pandas as pd
    df = pd.DataFrame({"strike": K_arr, "mid": p_mkt})
    print(f"✓ Datos referencia: S0={S0}, r={r}, T={T}, n={len(df)}")
    return S0, r, T, df

def datos_desde_csv(ruta="/datalab/spx_quotedata.csv"):
    import re

    # ── Parámetros del mercado ────────────────────────────────
    S0 = 7408.5      # S&P 500 el día de descarga
    r  = 0.043       # T-bill 1 mes, mayo 2026
    T  = 125 / 365.0

    # ── Parseo del CSV ────────────────────────────────
    with open(ruta) as f:
        lines = [l.strip().strip('"') for l in f.readlines()]

    strikes, mids, ivs, volumes = [], [], [], []

    print(f"Debugging: S0={S0}")

    for i, line in enumerate(lines[1:]):
        parts = line.split(',')

        fields = []
        j = 0
        while j < len(parts):
            p = parts[j].strip().strip('"')
            if (j + 1 < len(parts) and
                    p.lstrip('-').isdigit() and
                    re.match(r'^\d{3}(\.\d+)?', parts[j+1].strip())):
                fields.append(p + parts[j+1].strip().strip('"'))
                j += 2
            else:
                fields.append(p)
                j += 1

        try:

            strike_str = fields[2].replace(',', '') if len(fields) > 2 and fields[2] else '0.0'
            bid_str    = fields[4].replace(',', '') if len(fields) > 4 and fields[4] else '0.0'
            ask_str    = fields[5].replace(',', '') if len(fields) > 5 and fields[5] else '0.0'
            vol_str    = fields[8].replace(',', '') if len(fields) > 8 and fields[8] else '0'
            iv_str     = fields[10].replace(',', '') if len(fields) > 10 and fields[10] else '0.0'

            strike = float(strike_str)
            bid    = float(bid_str)
            ask    = float(ask_str)
            mid    = (bid + ask) / 2.0 if bid > 0 and ask > 0 else 0.0 # Calculate mid from bid and ask
            volume = int(float(vol_str)) # Convert to float first to handle potential decimals, then int
            iv     = float(iv_str) if iv_str not in ['unch', 'N/A', ''] else 0.0 # No division by 100


            # Comprobar condiciones de filtros individuales
            cond_strike_low = (strike > 0.01 * S0)
            cond_strike_high = (strike < 1.50 * S0)
            cond_mid = (mid > 0.01)
            cond_iv = (iv > 1e-6)

            if cond_strike_low and cond_strike_high and cond_mid and cond_iv:
                strikes.append(strike)
                mids.append(mid)
                ivs.append(iv)
                volumes.append(volume)
            # else:
                # print(f"Line {i+1} -> Filtered out.") # Debugging print
        except Exception as e:
            print(f"Skipping line {i+1} due to parsing error: {e}, Line: {line}") # For debugging
            pass

    strikes = np.array(strikes)
    mids    = np.array(mids)
    ivs     = np.array(ivs)

    # ── Filtros de liquidez  ───────────────────────────────────
    mask = (
        (strikes > 0.01 * S0) &   # Adjusted lower moneyness bound
        (strikes < 1.50 * S0) &   # Adjusted upper moneyness bound
        (mids    > 0.01       ) &  # Adjusted minimum price
        (ivs     > 1e-6       )    # Adjusted minimum IV (to include very small values like 1.0e-05)
    )

    import pandas as pd
    df = pd.DataFrame({
        "strike": strikes[mask],
        "mid"   : mids[mask]
    }).reset_index(drop=True)

    print(f"✓ CSV leído correctamente")
    print(f"  S0 = {S0},  r = {r},  T = {T:.4f} ({T*365:.0f} días)")
    print(f"  Opciones seleccionadas: {len(df)}")
    if not df.empty:
        print(f"  Strikes: [{df.strike.min():.0f}, {df.strike.max():.0f}]")
        print(f"  Moneyness: [{df.strike.min()/S0:.3f}, "
              f"{df.strike.max()/S0:.3f}]")
        print(f"  Precios:  [{df.mid.min():.2f}, {df.mid.max():.2f}]")
    else:
        print("  No options selected after filtering.")

    return S0, r, T, df

csv_path = "/content/drive/MyDrive/Codigo TFM/spx_quotedata.csv"

try:
    with open(csv_path, 'r') as f:
        print(f"First 10 lines of {csv_path}:\n")
        for i, line in enumerate(f):
            print(line.strip())
            if i >= 9: # Print first 10 lines (0-indexed)
                break
except FileNotFoundError:
    print(f"Error: The file '{csv_path}' was not found. Please ensure it is uploaded or the path is correct.")
except Exception as e:
    print(f"An error occurred while reading the file: {e}")

# =======================================================================
#  MODELOS DE VALORACIÓN
# =======================================================================

def bs_call(S, K, T, r, sig):
    d1 = (np.log(S/K)+(r+0.5*sig**2)*T)/(sig*np.sqrt(T))
    d2 = d1 - sig*np.sqrt(T)
    return S*norm.cdf(d1) - K*np.exp(-r*T)*norm.cdf(d2)

def heston_cf(u, S, T, r, kappa, theta, sv, rho, v0):
    i = 1j
    xi  = kappa - rho * sv * i * u
    d   = np.sqrt(xi**2 + sv**2 * u * (u + i))
    g   = (xi - d) / (xi + d)
    edt = np.exp(-d * T)
    C = (r * i * u * T
         + kappa * theta / sv**2
           * ((xi - d) * T - 2 * np.log((1 - g * edt) / (1 - g))))
    D = (xi - d) / sv**2 * (1 - edt) / (1 - g * edt)
    return np.exp(C + D * v0 + i * u * np.log(S * np.exp(r * T)))


def heston_integrand(u, lnK_arr, S, T, r, kappa, theta, sv, rho, v0):
    # P2: phi evaluada en u
    phi2 = heston_cf(u, S, T, r, kappa, theta, sv, rho, v0)
    # P1: phi evaluada en u - i  (cambio de numerario)
    phi1 = heston_cf(u - 1j, S, T, r, kappa, theta, sv, rho, v0)
    phi1_0 = heston_cf(-1j,  S, T, r, kappa, theta, sv, rho, v0)

    # e^{-iu ln K} para cada strike simultáneamente
    e_lnK = np.exp(-1j * u * lnK_arr)

    I2 = np.real(e_lnK * phi2  / (1j * u))      # integrando P2
    I1 = np.real(e_lnK * phi1  / (1j * u * phi1_0))  # integrando P1

    return np.concatenate([I2, I1])

def heston_call_vec(S, K_arr, T, r, kappa, theta, sv, rho, v0,
                    upper=150):
    K_arr = np.asarray(K_arr)
    n     = len(K_arr)
    lnK   = np.log(K_arr)

    result, _ = quad_vec(
        lambda u: heston_integrand(u, lnK, S, T, r,
                                  kappa, theta, sv, rho, v0),
        1e-5, upper,
        epsabs=1e-5, epsrel=1e-5
    )

    I2 = result[:n]
    I1 = result[n:]

    P2 = 0.5 + I2 / np.pi
    P1 = 0.5 + I1 / np.pi

    precios = S * P1 - K_arr * np.exp(-r * T) * P2
    floor   = np.maximum(S - K_arr * np.exp(-r * T), 0)
    return np.maximum(precios, floor)


def heston_call(S, K, T, r, kappa, theta, sv, rho, v0):
    """
    Precio call europea bajo Heston vía inversión de Fourier
    (Gil-Pelaez 1951, Heston 1993).
    """
    lnK = np.log(K)
    def I(u, j):
        phi = heston_cf(u-(1j if j==1 else 0), S, T, r, kappa, theta, sv, rho, v0)
        p0  = heston_cf(-(1j if j==1 else 0),  S, T, r, kappa, theta, sv, rho, v0)
        return np.real(np.exp(-1j*u*lnK)*phi/(1j*u*p0))
    P1,_ = quad(lambda u: I(u,1), 1e-5, 150, limit=80)
    P2,_ = quad(lambda u: I(u,2), 1e-5, 150, limit=80)
    return max(S*(0.5+P1/np.pi) - K*np.exp(-r*T)*(0.5+P2/np.pi),
               max(S-K*np.exp(-r*T), 0))

def vasicek_bond(r0, T, a, b, sr):
    """Precio bono cupón cero bajo Vasicek"""
    B = (1-np.exp(-a*T))/a
    bstar = b - sr**2/(2*a**2)
    A = bstar*(B-T) - sr**2/(4*a)*B**2
    return np.exp(A + B*r0)

def vh_call_approx(S, K, T, r0, kappa, theta, sv, rho, v0,
                   a, b, sr):
    """
    Precio call bajo Vasicek-Heston.
    """
    P    = vasicek_bond(r0, T, a, b, sr)
    r_fw = -np.log(P) / T

    var_adj = sr**2 / (2*a**3) * (
        2*a*T - 3 + 4*np.exp(-a*T) - np.exp(-2*a*T))

    # Ajuste máximo: no más del 50% de la varianza original
    var_adj = np.clip(var_adj, 0, 0.5 * sv**2)
    sv_adj  = np.sqrt(sv**2 + var_adj)

    # Precio Heston con tasa forward y vol ajustada
    p_hes = heston_call_vec(S, np.array([K]), T, r_fw,
                             kappa, theta, sv_adj, rho, v0)[0]

    # Reescalar por el ratio de factores de descuento
    factor = np.exp(-r0*T) / np.exp(-r_fw*T)
    precio  = p_hes * factor

    floor = max(S - K*np.exp(-r0*T), 0.0)
    return max(float(precio), floor)

# ═══════════════════════════════════════════════════════════════════
#  CALIBRACIÓN
# ═══════════════════════════════════════════════════════════════════

def calibrar_bs(S, K_arr, T, r, p_mkt):
    res = minimize(lambda p: sum((bs_call(S,K,T,r,p[0])-pm)**2
                                 for K,pm in zip(K_arr,p_mkt)),
                   [0.20], method='Nelder-Mead',
                   options={'xatol':1e-8,'fatol':1e-10,'maxiter':5000})
    return res.x[0], res.fun


from scipy.optimize import minimize


def calibrar_heston(S, K_arr, T, r, p_mkt):

    def obj(p):
        kappa, theta, sv, rho, v0 = p
        if (kappa <= 0 or theta <= 0 or sv <= 0
                or v0 < 0.001
                or abs(rho) >= 1):
            return 1e10
        pen = max(0, sv**2 - 2*kappa*theta) * 1e4
        try:
            pm = heston_call_vec(S, K_arr, T, r,
                                  kappa, theta, sv, rho, v0)
            w  = 1.0 / np.maximum(p_mkt, 1e-4)
            return float(np.sum(w * (pm - p_mkt)**2)) + pen
        except Exception:
            return 1e10

    idx_atm = np.argmin(np.abs(K_arr - S))
    sigma0  = np.clip(np.sqrt(2*np.pi/T) * p_mkt[idx_atm] / S,
                      0.05, 0.80)
    v0_est  = sigma0**2

    v0_est = max(v0_est, 0.01)

    starts = [
        [1.0,  v0_est,       sigma0*0.3,  -0.7,  v0_est      ],
        [2.0,  v0_est,       sigma0*0.5,  -0.5,  v0_est      ],
        [0.5,  v0_est*1.2,   sigma0*0.2,  -0.8,  v0_est      ],
        [3.0,  v0_est*0.8,   sigma0*0.4,  -0.6,  v0_est*0.8  ],
        [1.5,  v0_est,       sigma0*0.15, -0.4,  v0_est*1.2  ],
        [4.0,  v0_est*0.5,   sigma0*0.6,  -0.9,  v0_est*0.5  ],
        [0.8,  v0_est*1.5,   sigma0*0.25, -0.3,  v0_est*1.5  ],
    ]

    mejor_val    = np.inf
    mejor_params = starts[0]

    for x0 in starts:
        res = minimize(obj, x0, method='Nelder-Mead',
                       options={'xatol':1e-4, 'fatol':1e-4,
                                'maxiter':2000, 'adaptive':True})
        if res.fun < mejor_val:
            mejor_val    = res.fun
            mejor_params = res.x

    # ── refinamiento desde el mejor punto ─────────────
    res_final = minimize(obj, mejor_params, method='Nelder-Mead',
                         options={'xatol':1e-7, 'fatol':1e-9,
                                  'maxiter':5000, 'adaptive':True})

    return res_final.x, res_final.fun

def calibrar_vasicek(S, K_arr, T, r, p_mkt, hp):
    from scipy.optimize import minimize

    kappa, theta, sv, rho, v0 = hp

    def obj(p):
        a, b, sr = p
        try:
            pm = np.array([vh_call_approx(S, K, T, r,
                                           kappa, theta, sv, rho, v0,
                                           a, b, sr)
                           for K in K_arr])
            w = 1.0 / np.maximum(p_mkt, 1e-4)
            return float(np.sum(w * (pm - p_mkt)**2))
        except Exception:
            return 1e10

    # Bounds estrictos
    # a  ∈ [0.01, 5.0]  : reversión lenta a rápida (no instantánea)
    # b  ∈ [0.001, 0.15] : tipo largo plazo entre 0.1% y 15%
    # sr ∈ [0.001, 0.05] : vol del tipo entre 0.1% y 5%
    bounds = [(0.01, 5.0),
              (0.001, 0.15),
              (0.001, 0.05)]

    # Múltiples puntos iniciales nos evitan mínimos locales
    starts = [
        [0.5,  r,     0.01],
        [1.0,  r,     0.02],
        [2.0,  r,     0.005],
        [0.2,  r*1.1, 0.015],
        [3.0,  r*0.9, 0.03],
    ]

    mejor_val    = np.inf
    mejor_params = starts[0]

    for x0 in starts:
        try:
            res = minimize(obj, x0,
                           method='L-BFGS-B',
                           bounds=bounds,
                           options={'ftol':1e-9,
                                    'gtol':1e-7,
                                    'maxiter':2000})
            if res.fun < mejor_val:
                mejor_val    = res.fun
                mejor_params = res.x
        except Exception:
            pass

    return np.array(mejor_params), mejor_val

# ═══════════════════════════════════════════════════════════════════
#  VOLATILIDAD IMPLÍCITA
# ═══════════════════════════════════════════════════════════════════

def vol_impl(precio, S, K, T, r):
    try:
        return brentq(lambda s: bs_call(S,K,T,r,s)-precio, 0.001, 5.0, xtol=1e-6)
    except:
        return np.nan

# ═══════════════════════════════════════════════════════════════════
#  GRIEGAS
# ═══════════════════════════════════════════════════════════════════

def griegas_bs(S, K, T, r, sig):
    d1=(np.log(S/K)+(r+0.5*sig**2)*T)/(sig*np.sqrt(T)); d2=d1-sig*np.sqrt(T)
    return {'Delta':norm.cdf(d1),
            'Gamma':norm.pdf(d1)/(S*sig*np.sqrt(T)),
            'Vega' :S*norm.pdf(d1)*np.sqrt(T),
            'Theta':-S*norm.pdf(d1)*sig/(2*np.sqrt(T))-r*K*np.exp(-r*T)*norm.cdf(d2)}

# ═══════════════════════════════════════════════════════════════════
#  MAIN
# ═══════════════════════════════════════════════════════════════════

def main():
    print("="*60)
    print("  Capítulo 6 — Aplicación empírica")
    print("="*60)

    # Datos
    #res = descargar_opciones()
    #S0, r, T, df = res if res else datos_referencia()
    S0, r, T, df = datos_desde_csv("/content/drive/MyDrive/Codigo TFM/spx_quotedata.csv")
    K_arr   = df["strike"].values.astype(float)
    p_mkt   = df["mid"].values.astype(float)
    moneyness = K_arr / S0

    # ── Restringir al rango líquido ───────────────────────────────
    # Solo strikes entre 88% y 112% del ATM
    # Fuera de este rango los modelos son numéricamente inestables
    # y las opciones tienen poca liquidez real
    mask_rango = (K_arr >= 0.88 * S0) & (K_arr <= 1.12 * S0)
    K_arr = K_arr[mask_rango]
    p_mkt = p_mkt[mask_rango]
    print(f"  Strikes tras filtro ±12%: {len(K_arr)}")

    # Excluimos también strikes con precio de mercado menor a 5
    mask_liquidez = p_mkt >= 5.0
    K_arr = K_arr[mask_liquidez]
    p_mkt = p_mkt[mask_liquidez]
    print(f"  Strikes tras filtro liquidez (precio>5$): {len(K_arr)}")

    moneyness = K_arr / S0

    # Calibración Black-Scholes con todos los strikes
    print("\n[2] Calibrando modelos...")
    sigma_bs, sse_bs = calibrar_bs(S0, K_arr, T, r, p_mkt)
    print(f"  B-S (full data):  sigma={sigma_bs:.4f}  SSE={sse_bs:.2f}")

    # ── Submuestreo para calibración Heston y VH ─────────────────
    # Usamos solo 20 strikes uniformemente distribuidos para calibrar
    # Heston y VH, y todos los datos completos para las figuras
    idx_cal = np.round(np.linspace(0, len(K_arr)-1, 20)).astype(int)
    K_cal    = K_arr[idx_cal]
    p_cal    = p_mkt[idx_cal]

    print(f"  Calibrando Heston y VH con {len(K_cal)} strikes (de {len(K_arr)} totales)")

    # Usamos K_cal y p_cal en las calibraciones de Heston y VH
    heston_params, sse_hes = calibrar_heston(S0, K_cal, T, r, p_cal)
    vh_params, sse_vh        = calibrar_vasicek(S0, K_cal, T, r, p_cal,
                                                 heston_params)

    kappa,theta_h,sv,rho,v0 = heston_params
    print(f"  Heston: k={kappa:.3f} th={theta_h:.4f} sv={sv:.3f} "
          f"rho={rho:.3f} v0={v0:.4f}  SSE={sse_hes:.2f}")

    a_v, b_v, sr_v = vh_params
    print(f"  VH:  a={a_v:.3f} b={b_v:.4f} sr={sr_v:.4f}  SSE={sse_vh:.2f}")

    feller = 2*kappa*theta_h - sv**2
    print(f"\n  Condicion de Feller: 2kth-sv^2 = {feller:.4f} "
          + ("(OK)" if feller>0 else "(VIOLADA)"))

    kappa, theta_h, sv, rho, v0 = heston_params
    print(f"\n  Verificación parámetros Heston:")
    print(f"    v0    = {v0:.6f}  {'✓' if v0 >= 0.001 else '✗ MUY PEQUEÑO'}")
    print(f"    sv    = {sv:.4f}  {'✓' if sv < 1.5 else '✗ MUY GRANDE'}")
    print(f"    Feller= {2*kappa*theta_h - sv**2:.4f} "
      f"{'✓' if 2*kappa*theta_h > sv**2 else '✗ VIOLADA'}")

    # Precios
    p_bs  = np.array([bs_call(S0,K,T,r,sigma_bs) for K in K_arr])
    p_hes = np.array([heston_call_vec(S0, np.array([K]), T, r, *heston_params)[0] for K in K_arr])
    p_vh  = np.array([vh_call_approx(S0,K,T,r,*heston_params,a_v,b_v,sr_v)
                      for K in K_arr])

    # Error medio absoluto (MAE) y error cuadrático medio (RMSE)
    e_bs  = np.abs(p_bs  - p_mkt) / np.maximum(p_mkt, 1)
    e_hes = np.abs(p_hes - p_mkt) / np.maximum(p_mkt, 1)
    e_vh  = np.abs(p_vh  - p_mkt) / np.maximum(p_mkt, 1)

    print("\nTabla 5.1 — Error de calibración (todos los strikes):")
    print(f"  {'Modelo':<20} {'MAE%':>8} {'RMSE%':>8} {'MaxErr%':>9}")
    print("  " + "-"*48)
    for nombre, e in [("Black-Scholes", e_bs),
                       ("Heston",        e_hes),
                       ("Vasicek-Heston",e_vh)]:
        mae  = np.mean(e) * 100
        rmse = np.sqrt(np.mean(e**2)) * 100
        mx    = np.max(e) * 100
        print(f"  {nombre:<20} {mae:8.2f} {rmse:8.2f} {mx:9.2f}")


    # Volatilidades implícitas
    vi_mkt = [vol_impl(p,S0,K,T,r) for p,K in zip(p_mkt, K_arr)]
    vi_hes = [vol_impl(p,S0,K,T,r) for p,K in zip(p_hes, K_arr)]
    vi_vh  = [vol_impl(p,S0,K,T,r) for p,K in zip(p_vh,  K_arr)]

    print("\n[3] Generando figuras...")

    # --- Fig 1: Precios + error relativo ---
    fig,axes=plt.subplots(1,2,figsize=(12,4.5))
    ax=axes[0]
    ax.plot(moneyness,p_mkt,'o',color='black',ms=4,label='Mercado',zorder=5)
    ax.plot(moneyness,p_bs, color=COLORS[0],ls='--',label='Black-Scholes')
    ax.plot(moneyness,p_hes,color=COLORS[1],ls='-.',label='Heston')
    ax.plot(moneyness,p_vh, color=COLORS[2],ls='-', label='Vasicek-Heston')
    ax.set_xlabel('Moneyness'); ax.set_ylabel('Precio call')
    ax.set_title('(a) Precios de opciones call europeas')
    ax.legend(); ax.grid(alpha=0.3)
    ax2=axes[1]
    for p_mod,lbl,col,ls in [(p_bs,'Black-Scholes',COLORS[0],'--'),
                               (p_hes,'Heston',COLORS[1],'-.'),
                               (p_vh,'Vasicek-Heston',COLORS[2],'-')]:
        ax2.plot(moneyness,100*np.abs(p_mod-p_mkt)/np.maximum(p_mkt,1),
                 color=col,ls=ls,label=lbl)
    ax2.set_xlabel('Moneyness'); ax2.set_ylabel('Error relativo (%)')
    ax2.set_title('(b) Error relativo respecto al mercado')
    ax2.legend(); ax2.grid(alpha=0.3)
    plt.tight_layout(); plt.savefig(f'{OUT}/fig1_precios.pdf',bbox_inches='tight'); plt.close()
    print("  fig1_precios.pdf OK")

    # --- Fig 2: Smile ---
    fig,ax=plt.subplots(figsize=(8,5))
    ax.plot(moneyness,[v*100 if v else np.nan for v in vi_mkt],
            'o',color='black',ms=4,label='Mercado')
    ax.plot(moneyness,[sigma_bs*100]*len(K_arr),color=COLORS[0],ls='--', # sigma_bs is the full data calibrated one
            label=f'Black-Scholes (sigma={sigma_bs:.3f})')
    ax.plot(moneyness,[v*100 if v else np.nan for v in vi_hes],
            color=COLORS[1],ls='-.',label='Heston')
    ax.plot(moneyness,[v*100 if v else np.nan for v in vi_vh],
            color=COLORS[2],ls='-', label='Vasicek-Heston')
    ax.set_xlabel('Moneyness'); ax.set_ylabel('Volatilidad implicita (%)')
    ax.set_title('Sonrisa de volatilidad implicita')
    ax.legend(); ax.grid(alpha=0.3)
    plt.tight_layout(); plt.savefig(f'{OUT}/fig2_smile.pdf',bbox_inches='tight'); plt.close()
    print("  fig2_smile.pdf OK")

    # --- Fig 3: Griegas ---
    bs_gr=[griegas_bs(S0,K,T,r,sigma_bs) for K in K_arr]
    eps_s=S0*0.001; eps_v=sv*0.01; eps_t=T*0.01
    hes_delta=[(heston_call_vec(S0+eps_s, np.array([K]),T,r,*heston_params)[0]-
                heston_call_vec(S0-eps_s, np.array([K]),T,r,*heston_params)[0])/(2*eps_s) for K in K_arr]
    hes_gamma=[(heston_call_vec(S0+eps_s, np.array([K]),T,r,*heston_params)[0]
                -2*heston_call_vec(S0, np.array([K]),T,r,*heston_params)[0]
                +heston_call_vec(S0-eps_s, np.array([K]),T,r,*heston_params)[0])/eps_s**2 for K in K_arr]
    hes_vega =[(heston_call_vec(S0, np.array([K]),T,r,kappa,theta_h,sv+eps_v,rho,v0)[0]
                -heston_call_vec(S0, np.array([K]),T,r,kappa,theta_h,sv-eps_v,rho,v0)[0])/(2*eps_v)
               for K in K_arr]
    hes_theta=[-(heston_call_vec(S0, np.array([K]),T+eps_t,r,*heston_params)[0]
                 -heston_call_vec(S0, np.array([K]),T-eps_t,r,*heston_params)[0])/(2*eps_t)
               for K in K_arr]
    fig,axes=plt.subplots(2,2,figsize=(12,8))
    datos_g=[([g['Delta'] for g in bs_gr],hes_delta,'(a) Delta'),
             ([g['Gamma'] for g in bs_gr],hes_gamma,'(b) Gamma'),
             ([g['Vega']  for g in bs_gr],hes_vega, '(c) Vega'),
             ([g['Theta'] for g in bs_gr],hes_theta,'(d) Theta')]
    for ax,(bs_y,hes_y,tit) in zip(axes.flat,datos_g):
        ax.plot(moneyness,bs_y, color=COLORS[0],ls='--',label='Black-Scholes')
        ax.plot(moneyness,hes_y,color=COLORS[1],ls='-.',label='Heston')
        ax.set_xlabel('Moneyness'); ax.set_title(tit)
        ax.legend(); ax.grid(alpha=0.3)
    plt.suptitle('Griegas: Black-Scholes vs. Heston')
    plt.tight_layout(); plt.savefig(f'{OUT}/fig3_griegas.pdf',bbox_inches='tight'); plt.close()
    print("  fig3_griegas.pdf OK")

    # --- Fig 4: Sensibilidad ---
    fig,axes=plt.subplots(2,2,figsize=(12,8)); mon=K_arr/S0
    # (a) rho
    ax=axes[0,0]
    for rv,ls in zip([-0.9,-0.5,0.0,0.5],['--','-.','--',':']):
        p=[heston_call_vec(S0,np.array([K]),T,r,kappa,theta_h,sv,rv,v0)[0] for K in K_arr]
        vi=[vol_impl(pi,S0,K,T,r) for pi,K in zip(p,K_arr)]
        ax.plot(mon,[v*100 if v else np.nan for v in vi],ls=ls,label=f'rho={rv}')
    ax.set_xlabel('Moneyness'); ax.set_ylabel('Vol. impl. (%)')
    ax.set_title('(a) Efecto de rho'); ax.legend(); ax.grid(alpha=0.3)
    # (b) sigma_v
    ax=axes[0,1]
    for sv_val,ls in zip([0.10,0.30,0.50,0.80],['--','-.','--',':']):
        p=[heston_call_vec(S0,np.array([K]),T,r,kappa,theta_h,sv_val,rho,v0)[0] for K in K_arr]
        vi=[vol_impl(pi,S0,K,T,r) for pi,K in zip(p,K_arr)]
        ax.plot(mon,[v*100 if v else np.nan for v in vi],ls=ls,label=f'$\\sigma_v={sv_val}$')
    ax.set_xlabel('Moneyness'); ax.set_ylabel('Vol. impl. (%)')
    ax.set_title('(b) Efecto de $\\sigma_v$'); ax.legend(); ax.grid(alpha=0.3)
    # (c) vencimiento
    ax=axes[1,0]
    for Tv,ls in zip([2/12,3/12,6/12,1.0],['--','-.','--',':']):
        p=[heston_call_vec(S0,np.array([K]),Tv,r,kappa,theta_h,sv,rho,v0)[0] for K in K_arr]
        vi=[vol_impl(pi,S0,K,Tv,r) for pi,K in zip(p,K_arr)]
        ax.plot(mon,[v*100 if v else np.nan for v in vi],ls=ls,
                label=f'T={int(Tv*12)}m')
    ax.set_xlabel('Moneyness'); ax.set_ylabel('Vol. impl. (%)')
    ax.set_title('(c) Evolucion de la sonrisa con el vencimiento')
    ax.legend(); ax.grid(alpha=0.3)
    # (d) sigma_r
    ax=axes[1,1]
    a_demo = 0.3    # reversión lenta → sigma_r tiene más efecto
    for sr, ls in zip([0.005, 0.02, 0.06, 0.12], ['--', '-.', '-', ':']):
        p = [vh_call_approx(S0, K, T, r, *heston_params,
                            a_demo, b_v, sr)
            for K in K_arr]
        vi = [vol_impl(pi, S0, K, T, r) for pi, K in zip(p, K_arr)]
        ax.plot(moneyness, [v*100 if v else np.nan for v in vi],
                ls=ls, label=f'$\\sigma_r={sr}$' ) # Changed label to fix typo and show sigma_r
    ax.set_xlabel('Moneyness'); ax.set_ylabel('Vol. impl. (%)')
    ax.set_title('(d) Efecto de $\\sigma_r$') # Changed title to fix typo and show sigma_r
    ax.legend(); ax.grid(alpha=0.3)
    plt.suptitle('Analisis de sensibilidad de parametros')
    plt.tight_layout(); plt.savefig(f'{OUT}/fig4_sensibilidad.pdf',bbox_inches='tight'); plt.close()
    print("  fig4_sensibilidad.pdf OK")

    # --- Fig 5: Impacto tipo estocastico ---
    fig,ax=plt.subplots(figsize=(8,5))
    p_h_base = np.array([heston_call_vec(S0, np.array([K]), T, r, *heston_params)[0] for K in K_arr])

    for sigma_r_test, col, ls in zip([0.01, 0.05, 0.10],
                                   COLORS, ['--', '-.', '-']):
        p_v = np.array([vh_call_approx(S0, K, T, r,
                                        *heston_params,
                                        a_v, b_v, sigma_r_test)
                        for K in K_arr])
        ax.plot(moneyness, p_v - p_h_base, color=col, ls=ls, label=f'$\\sigma_r={sigma_r_test}$' ) # Changed label to fix typo and show sigma_r


    ax.axhline(0,color='black',lw=0.8,ls=':')

    ax.set_xlabel('Moneyness'); ax.set_ylabel('Diferencia de precio (VH - Heston)')
    ax.set_title('Impacto del tipo de interes estocastico sobre el precio de la call')
    ax.legend(); ax.grid(alpha=0.3)
    plt.tight_layout(); plt.savefig(f'{OUT}/fig5_impacto_tipo.pdf',bbox_inches='tight'); plt.close()
    print("  fig5_impacto_tipo.pdf OK")

    # --- Tabla de precios ---
    print("\n[4] Tabla 5.2 — Precios call europeas (seleccion ATM):")
    print(f"  {'K/S0':>7} {'Mercado':>9} {'BS':>9} {'Heston':>9} {'VH':>9}"
          f" {'ErrBS%':>8} {'ErrH%':>8} {'ErrVH%':>8}")
    print("  "+"-"*68)

    idx_tabla = np.round(np.linspace(0, len(K_arr)-1, 15)).astype(int)

    print(f"{'K/S0':>7} {'Mercado':>9} {'BS':>9} {'Heston':>9} {'VH':>9}"
          f" {'ErrBS%':>8} {'ErrH%':>8} {'ErrVH%':>8}")
    print("-"*68)
    for i in idx_tabla:
        K   = K_arr[i]
        mkt = p_mkt[i]
        print(f"{K/S0:7.3f} {mkt:9.2f} {p_bs[i]:9.2f} {p_hes[i]:9.2f} "
              f"{p_vh[i]:9.2f} "
              f"{100*abs(p_bs[i]-mkt)/max(mkt,1):8.2f} "
              f"{100*abs(p_hes[i]-mkt)/max(mkt,1):8.2f} "
              f"{100*abs(p_vh[i]-mkt)/max(mkt,1):8.2f}")

    print(f"\nFiguras en: ./ {OUT}/")
    print("  fig1_precios.pdf      Precios y error relativo")
    print("  fig2_smile.pdf        Sonrisa de volatilidad implicita")
    print("  fig3_griegas.pdf      Delta, Gamma, Vega, Theta")
    print("  fig4_sensibilidad.pdf Analisis de sensibilidad")
    print("  fig5_impacto_tipo.pdf Impacto del tipo de interes estocastico")

if __name__ == "__main__":
    main()



